export const GET_INFO_SAGA = 'GET_INFO_SAGA';
export const SET_INFO_SAGA = 'SET_INFO_SAGA';
export const SET_INFO_SAGA_ERROR = 'SET_INFO_SAGA_ERROR'
export const  SET_INFO_SAGA_LOADING = 'SET_INFO_SAGA_LOADING'