export const GET_GRAPH_SAGA = 'GET_GRAPH_SAGA';
export const SET_GRAPH_SAGA = 'SET_GRAPH_SAGA';
export const SET_GRAPH_SAGA_LOADING = 'SET_GRAPH_SAGA_LOADING';
export const SET_GRAPH_SAGA_ERROR = 'SET_GRAPH_SAGA_ERROR';

